"""English for episode 1 (keys are the Chinese strings in ep01_intro.py)."""

EN = {
    # module
    "晶体管": "Transistors",
    "机器码": "Machine code",
    "汇编语言": "Assembly language",
    "硬件架构（框图）": "Architecture (block diagrams)",
    "逻辑门": "Logic gates",
    "高级语言（C）": "High-level language (C)",
    # construct
    "抽象：高级语言 → 汇编 → 机器码 → 框图 → 逻辑门 → 晶体管":
        "Abstraction: C → assembly → machine code → block diagrams → gates → transistors",
    "ISA 是软件和硬件之间的接口": "The ISA is the interface between software and hardware",
    "五大部件：控制、数据通路、内存、输入、输出": "Five components: control, datapath, memory, input, output",
    "寄存器只有 128 字节，却比 DRAM 快 50–500 倍": "Registers: only 128 bytes, yet 50–500× faster than DRAM",
    "RISC：指令少而简单；RISC-V 开源、免授权费": "RISC: few, simple instructions; RISC-V is open and license-free",
    # abstraction
    "伟大思想 #1：抽象": "Great Idea #1: Abstraction",
    "CS61C 的第一个伟大思想：抽象。计算机系统从上到下，分成一层又一层。":
        "Great Idea #1 of CS61C: abstraction. A computer system is built as a stack of layers, from top "
        "to bottom.",
    # focus
    "最上层是高级语言，比如 C。": "At the top is a high-level language, such as C.",
    "编译器": "compiler",
    "编译器把它翻译成汇编语言……": "A compiler translates it into assembly language…",
    "汇编器": "assembler",
    "……汇编器再把它变成机器码：机器能直接读懂的 0 和 1。":
        "…and an assembler turns that into machine code: 1s and 0s the machine can read directly.",
    "再往下是硬件：先是用框图描述的架构，比如两个寄存器的值送进一个加法器。":
        "Below that is hardware. First, the architecture as block diagrams: say, two registers feeding an"
        " adder.",
    "放大加法器，里面是逻辑门：两个比特相加，异或门给出和，与门给出进位。":
        "Zoom into the adder and you find logic gates: adding two bits, an XOR gate gives the sum and an "
        "AND gate the carry.",
    "再放大一个逻辑门：它由晶体管搭成。这是最底层。": "Zoom into one gate: it's built from transistors. That's the bottom layer.",
    "相邻两层之间都有定义清晰的接口：只要遵守接口，就不必关心下一层的细节。":
        "Between neighboring layers is a well-defined interface: follow it, and you needn't care about "
        "the details below.",
    # half_adder
    "和": "sum",
    "进位": "carry",
    "1 位半加器": "1-bit half adder",
    # isa
    "软件": "Software",
    "硬件": "Hardware",
    "指令集架构（ISA）": "Instruction Set Architecture (ISA)",
    "本系列关注软件和硬件之间的接口：指令集架构（ISA）。":
        "This series focuses on the interface between software and hardware: the instruction set "
        "architecture (ISA).",
    "ISA 规定了：": "An ISA specifies:",
    "寄存器": "Registers",
    "数据类型": "Data types",
    "机器语言：指令如何用比特表示": "Machine language: their bit encoding",
    "汇编语言：有哪些指令": "Assembly language: the instructions",
    "内存寻址方式": "Memory addressing",
    "输入输出模型": "Input/output model",
    "ISA 规定了汇编语言有哪些指令、它们怎样编码成比特，以及寄存器、数据类型、内存寻址、输入输出等架构特性。":
        "An ISA specifies the assembly instructions, how they're encoded in bits, and architectural "
        "features such as registers, data types, memory addressing and I/O.",
    "应用程序": "Applications",
    "操作系统": "Operating system",
    "按 ISA 编写": "Written to the ISA",
    "按 ISA 设计": "Designed to the ISA",
    "程序和编译器以 ISA 为标准来编写；CPU 等硬件也以同一个 ISA 为标准来设计。":
        "Programs and compilers are written to the ISA as a standard; CPUs and other hardware are "
        "designed to that same standard.",
    "所以，程序能在任何遵循同一 ISA 的 CPU 上运行。本系列要学的 ISA，叫作 RISC-V。":
        "So a program can run on any CPU that follows the same ISA. The ISA this series studies is "
        "RISC-V.",
    # why_assembly
    "为什么要学汇编？": "Why learn assembly?",
    "C 代码": "C code",
    "汇编": "Assembly",
    "很少手写": "rarely hand-written",
    "汇编大多由编译器生成，很少有人手写。那为什么还要学它？":
        "Assembly is mostly generated by compilers; few people write it by hand. So why learn it?",
    "程序员平庸还是优秀，就看懂不懂汇编": "Mediocre vs. excellent programmers: do they know assembly?",
    "2004 年 Slashdot 上有篇帖子甚至说：程序员平庸还是优秀，就看懂不懂汇编。":
        "A 2004 Slashdot post even claimed that knowing assembly is what separates mediocre programmers "
        "from excellent ones.",
    "懂汇编 → 懂计算机怎样执行指令": "Know assembly → know how the computer executes instructions",
    "成本更低": "Cheaper",
    "更快": "Faster",
    "更省资源": "Leaner",
    "懂汇编，就懂计算机怎样执行指令；用高级语言也能写出更快、更省资源、成本更低的程序。":
        "Knowing assembly means knowing how the computer executes instructions, so even in a high-level "
        "language you write faster, leaner, cheaper programs.",
    # von_neumann
    "冯·诺依曼结构": "The von Neumann Architecture",
    "处理器（CPU）": "Processor (CPU)",
    "控制单元": "Control",
    "数据通路": "Datapath",
    "内存": "Memory",
    "程序": "Program",
    "数据": "Data",
    "输入输出（I/O）": "Input/Output (I/O)",
    "输入": "Input",
    "键盘等": "keyboards…",
    "显示器等": "displays…",
    "输出": "Output",
    "使能": "enable",
    "写入数据": "write data",
    "地址": "address",
    "读出数据": "read data",
    "学 ISA 之前，先来看计算机的基本布局：冯·诺依曼结构。":
        "Before learning an ISA, let's look at the basic layout of a computer: the von Neumann "
        "architecture.",
    "处理器（CPU）负责计算，由两部分组成：控制单元（control）和数据通路（datapath）。":
        "The processor (CPU) does the computing. It has two parts: the control unit and the datapath.",
    "数据通路的主角，是寄存器和负责运算的算术逻辑单元（ALU）。":
        "The datapath's main parts are the registers and the arithmetic logic unit (ALU), which does the "
        "math.",
    "处理器之外，是存放程序和数据的内存（memory），以及键盘、显示器这样的输入输出设备（I/O）。":
        "Outside it are memory, which holds both program and data, and input/output (I/O) devices like "
        "keyboards and displays.",
    "控制、数据通路、内存、输入、输出：这就是计算机的五大部件。":
        "Control, datapath, memory, input, output: the five components of a computer.",
    "处理器发出地址来读写内存；“使能”信号保证只读的时候不会误改内存。":
        "The processor sends an address to read or write memory; an \"enable\" signal keeps a read from "
        "changing memory.",
    # clock_and_light
    "寄存器与内存": "Registers and Memory",
    "4 GHz：每秒 40 亿个周期": "4 GHz: 4 billion cycles per second",
    "处理器非常快：4 GHz 的处理器，一个时钟周期只有 0.25 纳秒。":
        "Processors are fast: at 4 GHz, one clock cycle lasts just 0.25 nanoseconds.",
    "光速 ≈ 30 万公里/秒": "Speed of light ≈ 300,000 km/s",
    "这有多短？光速约每秒 30 万公里，而 0.25 纳秒只够光走 7.5 厘米。":
        "How short is that? Light travels about 300,000 km per second, yet in 0.25 ns it covers only 7.5 "
        "cm.",
    "数据哪怕只在 10 厘米外，光也要跑约 0.3 纳秒，超过一个周期。所以数据必须离处理器很近。":
        "Even data just 10 cm away takes light about 0.3 ns to reach: more than a cycle. So data must sit"
        " close to the processor.",
    "超过一个周期": "more than one cycle",
    "好在芯片本身远小于 10 厘米": "Luckily, chips are much smaller than 10 cm",
    # chip_diagram
    "处理器": "Processor",
    "内存（DRAM）": "Memory (DRAM)",
    # two_kinds
    "因此，现代计算机至少有两种存数据的硬件。一是寄存器：在处理器内部，空间小，但快如闪电。":
        "So every modern computer has at least two kinds of hardware for data. First, registers: inside "
        "the processor, small, but lightning fast.",
    "极快，但空间有限": "very fast, but tiny",
    "约 100 ns ≈ 400 个周期": "≈ 100 ns ≈ 400 cycles",
    "大得多，但慢": "much bigger, but slow",
    "二是内存：在处理器之外，大得多，但访问一次约 100 纳秒，相当于 400 个周期。":
        "Second, memory: outside the processor and much larger, but one access takes about 100 ns, or 400"
        " cycles.",
    # capacity
    "32 个寄存器 × 4 字节 = 128 字节": "32 registers × 4 bytes = 128 bytes",
    "笔记本：2–64 GB": "Laptop: 2–64 GB",
    "服务器：可达 1 TB": "Server: up to 1 TB",
    "再比容量：32 个寄存器各 4 字节，总共才 128 字节；笔记本却有 2 到 64 GB 内存，服务器可达 1 TB。":
        "Now capacity: 32 registers × 4 bytes is just 128 bytes, while a laptop has 2 to 64 GB of "
        "memory, and a server up to 1 TB.",
    # scr
    "把 128 字节画成小方块；同样比例下，64 GB 内存的面积约是它的 5 亿倍，小方块连一个像素都不到。":
        "Draw 128 bytes as a square. At this scale, 64 GB has about 500 million times the area: the "
        "square shrinks below a pixel.",
    "缩小倍数": "zoomed out",
    "64 GB 内存": "64 GB of memory",
    "128 B 寄存器": "128 B of registers",
    # band
    "DRAM 主存": "DRAM",
    "磁盘": "Disk",
    "伟大思想 #3：局部性原理 / 存储层次": "Great Idea #3: Locality / Memory Hierarchy",
    "在处理器核心里 · 约 128 字节": "In the processor core · about 128 bytes",
    "在另一块芯片上 · DDR3/4/5、HBM": "On a separate chip · DDR3/4/5, HBM",
    "几十美元就能买到好几 GB": "Many GB for a few tens of dollars",
    "更大，也更慢": "Bigger, and slower",
    "主存通常是另一块芯片上的 DRAM（如 DDR3/4/5、HBM），几十美元就能买好几 GB。":
        "Main memory is usually DRAM on a separate chip (DDR3/4/5, HBM): many gigabytes for a few tens of"
        " dollars.",
    "寄存器快 50–500 倍": "Registers: 50–500× faster",
    "越小，越快": "Smaller is faster",
    "但物理规律决定了：越小，越快。寄存器比 DRAM 快大约 50 到 500 倍。":
        "But physics dictates that smaller is faster: registers are roughly 50 to 500 times faster than "
        "DRAM.",
    # jim_gray
    "伯克利": "Berkeley",
    "洛杉矶": "Los Angeles",
    "萨克拉门托": "Sacramento",
    "内存慢 100 倍：开车去萨克拉门托": "Memory, 100× slower: drive to Sacramento",
    "寄存器：1 分钟（在脑子里）": "Register: 1 minute (in your head)",
    "内存慢 500 倍：去洛杉矶再回来": "Memory, 500× slower: to Los Angeles and back",
    "借用 Jim Gray 的比喻：从寄存器取数据，好比在脑子里回想一件事，花 1 分钟……":
        "Borrow Jim Gray's analogy: if getting data from a register is like recalling something in your "
        "head, taking one minute…",
    "……那么慢 100 倍的内存，就像为了一张忘带的纸，开车去萨克拉门托取回来。":
        "…then memory, 100 times slower, is like driving to Sacramento to fetch a piece of paper you "
        "forgot.",
    "要是慢 500 倍，就得开车去洛杉矶再回来，只为了取一个数据！":
        "At 500 times slower, you'd drive to Los Angeles and back, all for a single piece of data!",
    "寄存器数量很少，和处理器核心共用宝贵的芯片面积，非常昂贵。所以设计 ISA 像跳一支探戈：尽量在寄存器里算，少跑内存和磁盘。":
        "Registers are few, share precious chip area with the processor core, and are very expensive. So "
        "designing an ISA is a tango: compute in registers, and visit memory and disk sparingly.",
    # risc_cisc
    "指令越来越复杂": "ever more complex instructions",
    "写回内存": "write back",
    "相加": "add",
    "读内存": "read memory",
    "一条复杂指令": "one complex instruction",
    "ISA 该怎样设计？七八十年代的潮流是让指令越来越复杂：一条指令同时读内存、运算、写回。":
        "How should an ISA be designed? In the '70s and '80s, instructions grew ever more complex: one "
        "could read memory, compute and write back.",
    "硬件：复杂、昂贵": "Hardware: complex, costly",
    "CISC：复杂指令集计算机": "CISC: Complex Instruction Set Computer",
    "程序更短，访存也可能更少；代价是硬件复杂、造价高。这类架构后来被称为 CISC：复杂指令集计算机。":
        "Programs got shorter, maybe with fewer memory accesses, but the hardware was complex and costly."
        " Such designs were later dubbed CISC: Complex Instruction Set Computers.",
    "80 年代初，IBM 的 John Cocke 设计出 IBM 801：第一台精简指令集计算机（RISC）。":
        "In the early '80s, John Cocke at IBM designed the IBM 801: the first Reduced Instruction Set "
        "Computer (RISC).",
    "三条简单指令，每条只做一件事": "three simple instructions, one job each",
    "硬件：简单、快": "Hardware: simple, fast",
    "思路正相反：指令集小而简单，复杂操作交给软件和编译器，用简单指令拼出来。":
        "The opposite idea: keep the instruction set small and simple, and let software and compilers "
        "build complex operations from simple instructions.",
    "CISC：1 条复杂指令": "CISC: 1 complex instruction",
    "RISC：3 条简单指令": "RISC: 3 simple instructions",
    "时间": "time",
    "（示意）": "(schematic)",
    "指令条数变多了，但简单的硬件每秒能执行多得多的指令，整体反而更快。":
        "Programs need more instructions, but simple hardware runs far more of them per second, so they "
        "still finish sooner.",
    "先完成": "done first",
    "伯克利 RISC · 斯坦福 MIPS": "Berkeley RISC · Stanford MIPS",
    "RISC 项目": "RISC project",
    "MIPS 项目": "MIPS project",
    "伯克利的 Dave Patterson 和斯坦福的 John Hennessy 把它推向极致，同时做出了 RISC 和 MIPS 项目。":
        "Dave Patterson at Berkeley and John Hennessy at Stanford took the idea all the way, building the"
        " RISC and MIPS projects side by side.",
    "图灵奖": "Turing Award",
    "三位先驱后来都获得了图灵奖：Cocke 在 1987 年，Patterson 和 Hennessy 在 2017 年。":
        "All three pioneers went on to win the Turing Award: Cocke in 1987, Patterson and Hennessy in "
        "2017.",
    "Intel i3/i5/i7/i9、许多 AMD 处理器": "Intel i3/i5/i7/i9, many AMD chips",
    "许多 Windows 电脑": "many Windows PCs",
    "很多手机": "many phones",
    "苹果自研芯片（Apple silicon）": "Apple silicon",
    "都在快速发展": "both evolving fast",
    "如今 RISC 和 CISC 都很流行、都在快速发展：许多 Windows 电脑用 x86，很多手机和苹果自研芯片用 ARM。":
        "Today RISC and CISC both thrive and keep evolving: many Windows PCs run Intel's x86, while many "
        "phones and Apple's own chips use ARM.",
    # card
    "太复杂": "very complex",
    "缺少真正的编译器和软件": "no real compilers or software",
    "老旧或“自创”的 ISA": "Old or made-up ISAs",
    "教学总得选一个 ISA：x86 太复杂；老旧或“自创”的 ISA，又缺少真正的编译器和软件。":
        "A course has to pick an ISA. x86 is very complex, while old or made-up ISAs lack real compilers "
        "and software.",
    "RISC-V 诞生": "RISC-V born",
    "RISC-V 于 2010 年诞生在 UC Berkeley 的 Par Lab，由 Patterson 和 Krste Asanovic 发起；到 2020 年前后，连 MIPS 都转向了它。":
        "RISC-V was born in 2010 in UC Berkeley's Par Lab, started by Patterson and Krste Asanovic. "
        "Around 2020, even MIPS switched over to it.",
    "开源": "Open source",
    "免授权费": "License-free",
    "商用": "Commercial",
    "教学": "Teaching",
    "研究": "Research",
    "它受欢迎有两大原因：开源、免授权费。谁都能免费用，教学、研究、商用都行。":
        "It's popular for two reasons: it's open source and license-free. Anyone can use it for free, for"
        " teaching, research or commercial products.",
    "嵌入式微控制器": "Embedded microcontrollers",
    "仓库级超级计算机": "Warehouse-scale supercomputers",
    "全球学术界与产业界共同推动": "Backed by academia and industry worldwide",
    "全球学界和业界共同推动它。从嵌入式微控制器，到仓库级超级计算机，都已经有人用它来打造。":
        "Academia and industry worldwide back RISC-V, and it has been used to build everything from "
        "embedded microcontrollers to warehouse-scale supercomputers.",
    # rv32i
    "RV32I 与“绿卡”": "RV32I and the Green Card",
    "32 位": "32-bit",
    "基础整数指令集": "base integer instructions",
    "RISC-V 有 32、64、128 位等变体。本系列学 RV32I：32 位基础整数指令集；乘法等功能则放在 M 等扩展里。":
        "RISC-V comes in 32-, 64- and 128-bit variants. We'll study RV32I, the 32-bit base integer set; "
        "extras like multiplication live in extensions such as M.",
    "RV32I 基础指令集": "RV32I base instruction set",
    "M：乘除法": "M: multiply/divide",
    "F：浮点": "F: floating point",
    "可选扩展": "optional extensions",
    "RISC-V 绿卡": "RISC-V Green Card",
    "名字来自 1960 年代的 IBM 360 绿卡": "named after the 1960s IBM 360 green card",
    "整个架构的定义一页纸就能装下，叫作“绿卡”，名字来自 1960 年代著名的 IBM 360 绿卡。":
        "The whole architecture fits on a single page, the \"Green Card\", named after the famous IBM 360 "
        "green card of the 1960s.",
    "简洁、优雅，学汇编、学设计计算机都合适：这正是 CS61C 教它的原因。Go Bears！":
        "Simple and elegant, it's ideal for learning assembly and for designing computers. That's why "
        "CS61C teaches it. Go Bears!",
    # roadmap
    "全系列共 14 集。下一集，从一行 C 代码出发，看它怎样变成汇编，并认识 RISC-V 的寄存器。":
        "The series has 14 episodes. Next time, we start from one line of C, see how it becomes assembly,"
        " and meet RISC-V's registers.",
}
